fail-case-t109

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -26,8 +26,6 @@ jobs:
 
       - name: Install Angular@9
         run: npm install -g @angular/cli
-      
- 
     #   - name: Remove Existing 'ng-uikit-pro-standard'
     #     run:  rm -rf node_modules/ng-uikit-pro-standard
 
@@ -36,33 +34,33 @@ jobs:
     #          mkdir -p node_modules
     #          cp -r ng-uikit-pro-standard node_modules/
       - name: Build Code
-        run:  building ABC
-        # continue-on-error: true # Continue even if the build fails
-            # node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build
-        
-      - name: Check Build Status
-        id: build-status
-        run: echo "::set-output name=status::success" # Set the initial status as success
-
-      - name: Determine Build Status
-        id: check-build-status
         run: |
-          if [ -d "dist" ]; then
-            echo "::set-output name=status::success"
+          ng build
+          if [ $? -eq 0 ]; then
+             echo "::set-output name=status::success"
           else
-            echo "::set-output name=status::failure"
-          fi
+          echo "::set-output name=status::failure"
+          echo "Build hasbeen failed and PR is getting close"
+          PR_NUMBER="${{ github.event.pull_request.number }}"
+          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
+          PAYLOAD='{"state":"closed"}'
 
-      - name: Close or Deprecate PR
-        if: steps.check-build-status.outputs.status == 'failure'
-        run: |
-          # You can add your logic to close or deprecate the PR here
-          # Example: Close the PR
-          # GITHUB_TOKEN is a built-in token for authentication
-          curl -X POST \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -H "Content-Type: application/json" \
-            -d '{"state": "closed"}' \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
-    
-      
+          echo "Closing PR $PR_NUMBER due to build failure"
+          
+          # Close the PR
+          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -d "$PAYLOAD" \
+            "$API_URL"
+           fi
+        id: build-status
+        continue-on-error: true # Continue even if the build fails
+          # node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build
+  # close-pr:
+  #     needs: build
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #       - name: Close PR on Build Failure
+  #         if: ${{ needs.build.outputs.status == 'failure' }}
+          
+  
